// array of quotes
var quotes = [
	'It\'s safe to say that growth is an uncomfortable process <br>And pain is a necessary investment for progress. <br>- D Smoke (Last Supper)',
	'Roar, lion of the heart, and tear me open. <br>- Rumi',
	'I will not let anything get in the way of me and my competitive enthusiasm to win. <br>- Michael Jordan',
	'Why was I born, if it wasn\'t forever? <br>- Eug&egravene Ionesco (Exit the King)',
	'All I got is dreams. Nobody else believes. Nobody else can see. Nobody else but me. <br>- JAY Z',
	'Identity is a prison you can never escape, but the way to redeem your past is not to run from it, but to try to understand it, and use it as a foundation to grow. <br>- JAY Z',
	'They talk. We live. Who cares what they say? <br>- JAY Z',
	'People look at you strange, say you changed. Like you worked that hard to stay the same. <br>- JAY Z',
	'I believe everyone in the world is born with genius-level talent. Apply yourself to whatever you\'re genius at, and you can do anything in the world. <br>- JAY Z',
	'Money and power don\'t change you, they just further expose your true self. <br>- JAY Z',
	'May the best of your todays be the worst of your tomorrows. <br>- JAY Z',
	'I will not lose, for even in defeat, there\'s a valuable lesson learned, so it evens up for me. <br>- JAY Z',
	'I have been earnin\' and burnin\', snappin\' necks and cashin\' checks! <br>- William Ferrell (Step Brothers)',
	'It was a pleasure to burn. <br>- Ray Bradbury (Fahrenheit 451)',
	'It is of the highest importance in the art of detection to be able to recognize out of a number of facts which are incidental and which vital. <br>- Arthur Conan Doyle (Sherlock Holmes)',
	'Can\'t stop, won\'t stop. <br>- Diddy',
	'Sleep is good, he said, and books are better. <br>- George R. R. Martin',
	'The best way to predict the future is to invent it. <br>- Alan Kay',
	'At some point in life, the world\'s beauty becomes enough. <br>- Toni Morrison',
	'A lot of what goes on in the investment world is fighting yesterday\'s battles. <br>- David Harding',
	'To a mind that is still the whole universe surrenders. <br>- Lao Tzu',
	'Do or do not ... there is no try. <br>- Yoda (Star Wars)',
	'The market may be crazy, but that doesn\'t make you a psychiatrist. <br>- Meir Statman',
	'If the hive be disturbed by rash and stupid hands, instead of honey it will yield us bees. <br>- Ralph Waldo Emerson',
	'All the misfortunes of men come from only one thing: not knowing how to remain at rest in a room. <br>- Blaise Pascal',
	'One must still have chaos in oneself to be able to give birth to a dancing star. <br>- Friedrich Nietzsche',
	'There is but one solution to the intricate riddle of life; to improve ourselves, and contribute to the happiness of others. <br>- Mary Shelley',
	'The sun is but a morning star. <br>- Henry David Thoreau (Walden)',
	'The woods are lovely, dark and deep, <br>But I have promises to keep, <br>And miles to go before I sleep, <br>And miles to go before I sleep. <br>- Robert Frost (Stopping by Woods on a Snowy Evening)',
	'I am convinced that life is 10\% what happens to me and 90\% of how I react to it. <br>- Charles R. Swindoll',
	'There is no royal road to anything. One thing at a time, all things in succession. That which grows fast, withers as rapidly. That which grows slowly, endures. <br>- Josiah Gilbert Holland',
	'Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. <br>- William James (The Will to Believe)',
	'Great events turn on small hinges. <br>- Stephen King (The Institute)',
	'If you don\'t have time to read, you don\'t have the time (or the tools) to write. Simple as that. <br>- Stephen King',
	'Get busy living or get busy dying. <br>- Stephen King (Different Seasons)',
	'The road to hell is paved with adverbs. <br>- Stephen King (On Writing: A Memoir of the Craft)',
	'Fiction is the truth inside the lie. <br>- Stephen King',
	'The scariest moment is always just before you start. <br>- Stephen King (On Writing: A Memoir of the Craft)',
	'If you want to be a writer, you must do two things above all others: read a lot and write a lot. <br>- Stephen King',
	'You can, you should, and if you\'re brave enough to start, you will. <br>- Stephen King (On Writing: A Memoir of the Craft)',
	'Remember, Hope is a good thing, maybe the best of things, and no good thing ever dies. <br>- Stephen King (The Shawshank Redemption)',
	'Description begins in the writer\'s imagination, but should finish in the reader\'s. <br>- Stephen King (On Writing: A Memoir of the Craft)',
	'Even if you\'re on the right track, you\'ll get run over if you just sit there. <br>- Will Rogers',
	'Nurture your mind with great thoughts. To believe in the heroic makes heroes. <br>- Benjamin Disraeli',
	'Look at the sparrows; they do not know what they will do in the next moment. Let us literally live from moment to moment. <br>- Mahatma Gandhi',
	'Luck is a dividend of sweat. The more you sweat, the luckier you get. <br>- Ray Kroc',
	'When I let go of what I am, I become what I might be. <br>- Lao Tzu',
	'You may find the worst enemy or best friend in yourself. <br>- English Proverb',
	'Courage is the first of human qualities because it is the quality which guarantees all others. <br>- Winston Churchill',
	'Whoever loves much, performs much, and can accomplish much, and what is done in love is done well. <br>- Vincent Van Gogh',
	'The great thing in this world is not so much where you stand, as in what direction you are moving. <br>- Oliver Wendell Holmes',
	'Live each day as if your life had just begun. <br>- Johann Wolfgang Von Goethe',
	'Every truth passes through three stages before it is recognized. In the first, it is ridiculed. In the second, it is opposed. In the third, it is regarded as self evident. <br>- Arthur Schopenhauer',
	'The difference between a successful person and others is not lack of strength not a lack of knowledge but rather a lack of will. <br>- Vince Lombardi',
	'Either you run the day, or the day runs you. <br>- Jim Rohn',
	'If not us, who? If not now, when? <br>- John F. Kennedy',
	'Don\'t worry about failures, worry about the chances you miss when you don\'t even try. <br>- Jack Canfield (Chicken Soup for the Soul)',
	'Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending. <br>- Carl Bard',
	'You miss 100% of the shots you don\'t take. <br>- Wayne Gretzky <br>- Michael Scott. <br>- Steve Carell (The Office)',
	'The only way of finding the limits of the possible is by going beyond them into the impossible. <br>- Arthur C. Clarke',
	'Speak less than you know; have more than you show. <br>- William Shakespeare (King Lear)',
	'Do not go where the path may lead, go instead where there is no path and leave a trail. <br>- Ralph Waldo Emerson',
	'Many of life\'s failures are experienced by people who did not realize how close they were to success when they gave up. <br>- Thomas A. Edison',
	'The journey of a thousand miles begins with one step. <br>- Lao Tzu',
	'Every noble work is at first impossible. <br>- Thomas Carlyle',
	'Do not let what you cannot do interfere with what you can do. <br>- John Wooden',
	'It is not enough to aim, you must hit. <br>- Italian Proverb',
	'Every strike brings me closer to the next home run. <br>- Babe Ruth',
	'I am not a product of my circumstances. I am a product of my decisions. <br>- Stephen R. Covey',
	'Our lives begin to end the day we become silent about things that matter. <br>- Martin Luther King Jr.',
	'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great. <br>- Mark Twain',
	'Eighty percent of success is showing up. <br>- Woody Allen',
	'I have never in my life learned anything from any man who agreed with me. <br>- Dudley Field Malone',
	'We become what we think about. <br>- Earl Nightingale',
	'The mind is everything. What you think you become. <br>- Buddha',
	'Knowing is not enough, we must apply. Willing is not enough, we must do. <br>- Bruce Lee',
	'Knowledge will give you power, but character respect. <br>- Bruce Lee',
	'To hell with circumstances; I create opportunities. <br>- Bruce Lee',
	'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. <br>- Bruce Lee',
	'If you love life, don\'t waste time, for time is what life is made up of. <br>- Bruce Lee',
	'Mistakes are always forgivable, if one has the courage to admit them. <br>- Bruce Lee',
	'Empty your mind, be formless, shapeless, like water. <br>- Bruce Lee',
	'Do not let circumstances control you. You change your circumstances. <br>- Jackie Chan',
	'Don\'t try to be like Jackie. There is only one Jackie. Study computers instead. <br>- Jackie Chan',
	'To live is to suffer, to survive is to find some meaning in the suffering. <br>- Friedrich Nietzsche',
	'That which does not kill us makes us stronger. <br>- Friedrich Nietzsche',
	'Without music, life would be a mistake. <br>- Friedrich Nietzsche',
	'There are no facts, only interpretations. <br>- Friedrich Nietzsche',
	'Success is not final, failure is not fatal: it is the courage to continue that counts. <br>- Winston Churchill',
	'Never bend your head. Always hold it high. Look the world straight in the eye. <br>- Helen Keller',
	'Believe you can and you\'re halfway there. <br>- Theodore Roosevelt',
	'When you have a dream, you\'ve got to grab it and never let go. <br>- Carol Burnett',
	'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination. <br>- Jimmy Dean',
	'No matter what you\'re going through, there\'s a light at the end of the tunnel. <br>- Demi Lovato',
	'Life is like riding a bicycle. To keep your balance, you must keep moving. <br>- Albert Einstein',
	'Limit your "always" and your "nevers." <br>- Amy Poehler',
	'Nothing is impossible. The word itself says "I\'m possible!" <br>- Audrey Hepburn',
	'The best thing to hold onto in life is each other. <br>- Audrey Hepburn',
	'Everything I learned, I learned from the movies. <br>- Audrey Hepburn',
	'As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others. <br>- Audrey Hepburn',
	'You are never too old to set another goal or to dream a new dream. <br>- C. S. Lewis',
	'True humility is not thinking less of yourself; it is thinking of yourself less. <br>- C. S. Lewis',
	'Some day you will be old enough to start reading fairy tales again. <br>- C. S. Lewis',
	'We are what we believe we are. <br>- C. S. Lewis',
	'The struggle itself towards the heights is enough to fill a man\'s heart. One must imagine Sisyphus happy. <br>- Albert Camus',
	'In the depth of winter, I finally learned that within me there lay an invincible summer. <br>- Albert Camus',
	'I rebel; therefore I exist. <br>- Albert Camus',
	'Life is the sum of all your choices. <br>- Albert Camus',
	'Freedom is nothing but a chance to be better. <br>- Albert Camus',
	'Autumn is a second spring when every leaf is a flower. <br>- Albert Camus',
	'Blessed are the hearts that can bend; they shall never be broken. <br>- Albert Camus',
	'I hope for nothing. I fear nothing. I am free. <br>- Nikos Kazantzakis',
	'A person needs a little madness, or else they never dare cut the rope and be free. <br>- Nikos Kazantzakis',
	'You have your brush, you have your colors, you paint paradise, then in you go. <br>- Nikos Kazantzakis',
	'The real meaning of enlightenment is to gaze with undimmed eyes on all darkness. <br>- Nikos Kazantzakis',
	'Beauty is merciless. You do not look at it, it looks at you and does not forgive. <br>- Nikos Kazantzakis',
	'Every perfect traveler always creates the country where he travels. <br>- Nikos Kazantzakis',
	'Education is the most powerful weapon which you can use to change the world. <br>- Nelson Mandela',
	'When a man is denied the right to live the life he believes in, he has no choice but to become an outlaw. <br>- Nelson Mandela',
	'I learned that courage was not the absence of fear, but the triumph over it. <br>- Nelson Mandela',
	'It always seems impossible until it\'s done. <br>- Nelson Mandela',
	'Resentment is like drinking poison and then hoping it will kill your enemies. <br>- Nelson Mandela',
	'For to be free is not merely to cast off one\'s chains, but to live in a way that respects and enhances the freedom of others. <br>- Nelson Mandela',
	'Do not judge me by my successes, judge me by how many times I fell down and got back up again. <br>- Nelson Mandela',
	'Lead from the back, and let others believe they are in front. <br>- Nelson Mandela',
	'I am not a saint, unless you think of a saint as a sinner who keeps on trying. <br>- Nelson Mandela',
	'A winner is a dreamer who never gives up. <br>- Nelson Mandela',
	'Try to be a rainbow in someone else\'s cloud. <br>- Maya Angelou',
	'There is no greater agony than bearing an untold story inside you. <br>- Maya Angelou',
	'If you don\'t like something, change it. If you can\'t change it, change your attitude. <br>- Maya Angelou',
	'Nothing will work unless you do. <br>- Maya Angelou',
	'I know why the caged bird sings. <br>- Maya Angelou',
	'My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style. <br>- Maya Angelou',
	'You can\'t use up creativity. The more you use, the more you have. <br>- Maya Angelou',
	'You wanna fly, you got to give up the shit that weighs you down. <br>- Toni Morrison',
	'Love is or it ain\'t. Thin love ain\'t love at all. <br>- Toni Morrison',
	'You do not find the happy life. You make it. <br>- Camilla Eyring Kimball',
	'Sometimes you will never know the value of a moment, until it becomes a memory. <br>- Dr. Seuss',
	'The most wasted of days is one without laughter. <br>- E. E. Cummings',
	'You must do the things you think you cannot do. <br>- Eleanor Roosevelt',
	'It is never too late to be what you might have been. <br>- George Eliot',
	'Stay close to anything that makes you glad you are alive. <br>- Hafez',
	'It is what it is, trust me you get what you give, yeah. <br>- Drake (Blessings)',
	'Some people look for a beautiful place. Others make a place beautiful. <br>- Hazrat Inayat Khan',
	'Happiness often sneaks in through a door you didn\'t know you left open. <br>- John Barrymore',
	'We must be willing to let go of the life we planned so as to have the life that is waiting for us. <br>- Joseph Campbell',
	'Life changes very quickly, in a very positive way, if you let it. <br>- Lindsey Vonn',
	'Keep your face to the sunshine and you cannot see a shadow. <br>- Helen Keller',
	'Be the change that you wish to see in the world. <br>- Mahatma Gandhi',
	'An eye for eye only ends up making the whole world blind. <br>- Mahatma Gandhi',
	'Happiness is when what you think, what you say, and what you do are in harmony. <br>- Mahatma Gandhi',
	'Hate the sin, love the sinner. <br>- Mahatma Gandhi',
	'Where there is love there is life. <br>- Mahatma Gandhi',
	'Let us make our future now, and let us make our dreams tomorrow\'s reality. <br>- Malala Yousafzai',
	'A goal is a dream with a deadline. <br>- Napoleon Hill',
	'Patience, persistence and perspiration make an unbeatable combination for success. <br>- Napoleon Hill',
	'Strength and growth come only through continuous effort and struggle. <br>- Napoleon Hill',
	'Imagination rules the world. <br>- Napoleon Bonaparte',
	'Experience is the teacher of all things. <br>- Julius Caesar',
	'Very little is needed to make a happy life; it is all within yourself, in your way of thinking. <br>- Marcus Aurelius',
	'The soul becomes dyed with the color of its thoughts. <br>- Marcus Aurelius',
	'The universe is change; our life is what our thoughts make it. <br>- Marcus Aurelius',
	'If you look at what you have in life, you\'ll always have more. <br>- Oprah Winfrey',
	'Surround yourself with only people who are going to lift you higher. <br>- Oprah Winfrey',
	'Luck is a matter of preparation meeting opportunity. <br>- Oprah Winfrey',
	'The hardest thing to do is to be true to yourself, especially when everybody is watching. <br>- Dave Chappelle',
	'If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely. <br>- Roald Dahl',
	'No matter what people tell you, words and ideas can change the world. <br>- Robin Williams',
	'Each person must live their life as a model for others. <br>- Rosa Parks',
	'A champion is defined not by their wins but by how they can recover when they fall. <br>- Serena Williams',
	'I\'m really exciting. I smile a lot, I win a lot, and I\'m really sexy. <br>- Serena Williams',
	'Some people want it to happen, some wish it would happen, others make it happen. <br>- Michael Jordan',
	'I can accept failure, everyone fails at something. But I can\'t accept not trying. <br>- Michael Jordan',
	'I\'ve failed over and over and over again in my life and that is why I succeed. <br>- Michael Jordan',
	'Always turn a negative situation into a positive situation. <br>- Michael Jordan',
	'I\'ve always believed that if you put in the work, the results will come. <br>- Michael Jordan',
	'Everything negative - pressure, challenges - is all an opportunity for me to rise. <br>- Kobe Bryant',
	'You can\'t win unless you learn how to lose. <br>- Kareem Abdul-Jabbar',
	'I think that the good and the great are only separated by the willingness to sacrifice. <br>- Kareem Abdul-Jabbar',
	'Float like a butterfly, sting like a bee. <br>- Muhammad Ali',
	'Don\'t count the days, make the days count. <br>- Muhammad Ali',
	'Service to others is the rent you pay for your room here on earth. <br>- Muhammad Ali',
	'It\'s hard to be humble, when you\'re as great as I am. <br>- Muhammad Ali',
	'He who is not courageous enough to take risks will accomplish nothing in life. <br>- Muhammad Ali',
	'In my whole life, I have known no wise people (over a broad subject matter area) who didn\'t read all the time. <br>- Charles Munger',
	'To get what you want, you have to deserve what you want. The world is not yet a crazy enough place to reward a whole bunch of undeserving people. <br>- Charles Munger',
	'Spend each day trying to be a little wiser than you were when you woke up. <br>- Charles Munger',
	'It takes character to sit with all that cash and to do nothing. <br>- Charles Munger',
	'People calculate too much and think too little. <br>- Charles Munger',
	'We simply attempt to be fearful when others are greedy and to be greedy only when others are fearful. <br>- Warren Buffett',
	'Someone\'s sitting in the shade today because someone planted a tree a long time ago. <br>- Warren Buffett',
	'Risk comes from not knowing what you\'re doing. <br>- Warren Buffett',
	'Chains of habit are too light to be felt until they are too heavy to be broken. <br>- Warren Buffett',
	'I was never really good at anything except for the ability to learn. <br>- Kanye West',
	'You have to be able to accept failure to get better. <br>- Lebron James',
	'When you have that respect from your teammates, it makes it a lot more comfortable. <br>- Lebron James',
	'If you\'re not failing, you\'re not pushing your limits, and if you\'re not pushing your limits, you\'re not maximizing your potential. <br>- Ray Dalio',
	'It is far more common for people to allow ego to stand in the way of learning. <br>- Ray Dalio',
	'Truth - more precisely, an accurate understanding of reality - is the essential foundation for producing good outcomes. <br>- Ray Dalio',
	'I just want to be right; I don\'t care if the right answer comes from me. <br>- Ray Dalio',
	'Pain + Reflection = Progress <br>- Ray Dalio',
	'I have never met a man so ignorant that I couldn\'t learn something from him. <br>- Galileo Galilei',
	'Measure what is measurable, and make measurable what is not so. <br>- Galileo Galilei',
	'Simplicity is the ultimate sophistication. <br>- Leonardo da Vinci',
	'The noblest pleasure is the joy of understanding. <br>- Leonardo da Vinci',
	'He who has a why to live can bear almost any how. <br>- Friedrich Nietzsche',
	'Common sense is genius dressed in its working clothes. <br>- Ralph Waldo Emerson',
	'He that respects himself is safe from others. <br>- Henry Wadsworth Longfellow',
	'We are what we repeatedly do. Excellence, then, is not an act, but a habit. <br>- Aristotle',
	'Happiness depends upon ourselves. <br>- Aristotle',
	'All that we see or seem is but a dream within a dream. <br>- Edgar Allan Poe',
	'The first principle is that you must not fool yourself and you are the easiest person to fool. <br>- Richard Feynman',
	'Somewhere, something incredible is waiting to be known. <br>- Carl Sagan',
	'If you want to make an apple pie from scratch, you must first create the universe. <br>- Carl Sagan',
	'We\'re made of star stuff. We are a way for the cosmos to know itself. <br>- Carl Sagan',
	'Humor is everywhere, in that there\'s irony in just about anything a human does. <br>- Bill Nye',
	'You gotta love livin\', baby, \'cause dyin\' is a pain in the ass. <br>- Frank Sinatra',
	'If you can dream it, you can do it. <br>- Enzo Ferrari',
	'Success usually comes to those who are too busy to be looking for it. <br>- Henry David Thoreau',
	'Don\'t be afraid to give up the good to go for the great. <br>- John D. Rockefeller',
	'There is a powerful driving force inside every human being that, once unleashed, can make any vision, dream, or desire a reality. <br>- Tony Robbins',
	'Stop chasing the money and start chasing the passion. <br>- Tony Hsieh',
	'I find that the harder I work, the more luck I seem to have. <br>- Thomas Jefferson'
]

// generate a random quote
function getQuote() {
	var rand = Math.floor(Math.random() * (quotes.length));
	document.getElementById('retrievedQuote').innerHTML = quotes[rand];
}

// jQuery for backgrounds
$(document).ready(function() {

	  var clickCount = 0;
	  var backgroundImg = [
	    'images/background1.jpg',
	    'images/background2.jpg',
	    'images/background3.jpg',
	    'images/background4.jpg',
	    'images/background5.jpg',
	    'images/background6.jpg',
	    'images/background7.jpg',
	    'images/background8.jpg',
	    'images/background9.jpg',
	    'images/background10.jpg',
	    'images/background11.jpg',
	    'images/background12.jpg'
	  ];

	  $("#getBackground").on('click', function(){
	    var i = clickCount % backgroundImg.length;
	    $('body').css('background', 'url(' + backgroundImg[i] + ')' + 'no-repeat');
	    $('body').css('background-size', 'cover');
	    $('body').css('background-attachment', 'fixed');
	    clickCount++;
	  })
});
